apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-svc
spec:
  ports:
  - port: {{ .Values.service.clusterIPPort }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.deployment.name }}